<div class="container">
    <div class="container">
        <h1 class="page-header"><?php echo $this->translate('Testimonials') ?></h1>
        <div class="table-responsive">
            <table class="table  table-striped">
                <thead>
                    <tr>
                        <th><?php echo $this->translate('') ?></th>    
                        <th><?php echo $this->translate('#ID') ?></th>
                        <th><?php echo $this->translate('Vorname') ?></th>
                        <th><?php echo $this->translate('Nachname') ?></th>
                        <th><?php echo $this->translate('Email') ?></th>
                        <th><?php echo $this->translate('Company') ?></th>
                        <th><?php echo $this->translate('Position') ?></th>
                        <th><?php echo $this->translate('Statement') ?></th>
                        <th><?php echo $this->translate('Akitv') ?></th>      
                    </tr>
                </thead>
                <tbody>

                    <?php
                    foreach ($testimonials as $testimonial) {
                        ?>
                        <tr>
                            <td> 
                                <a class="btn btn-xs" href="<?php
                                echo $this->url('langroute/config/default', array(
                                    'controller' => 'testimonial', 'action' => 'edit', 'id' => $testimonial->getId()))
                                ?>">
                                    <span class="glyphicon glyphicon-edit"></span> <?php echo $this->translate('Ändern') ?>
                                </a>
                                <button type="button" class="btn btn-danger btn-xs" data-toggle="modal" data-target="#deleteUser">
                                    <?php echo $this->translate('Löschen') ?>
                                </button>
                            </td>
                            <td><?php echo $testimonial->getID() ?></td>
                            <td><?php echo $testimonial->getFirstname() ?></td>
                            <td><?php echo $testimonial->getLastname() ?></td>
                            <td><?php echo $testimonial->getEmail() ?></td>
                            <td><?php echo $this->translate($testimonial->getCompany()) ?></td>
                            <td><?php echo $this->translate($testimonial->getPosition()) ?></td>
                            <td><?php echo $this->translate($testimonial->getStatement()) ?></td>
                            <td><?php echo $this->ActiveHelper($testimonial->getActive()) ?></td>
                        </tr>
                    <?php } ?>
                </tbody>
            </table>
        </div>

    </div>
</div>

<div class="modal fade" id="deleteUser" tabindex="-1" role="dialog" aria-labelledby="<?php echo $this->translate('Testimonial löschen') ?>">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel"><?php echo $this->translate('Benutzer löschen') ?></h4>
            </div>
            <div class="modal-body">
                <?php echo $this->translate('Beim Bestätigen wird das Testimonial endgültig vom System gelöscht. Danach kann Dieses nicht mehr Wiederhergestellt werden.') ?>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal"><?php echo $this->translate('Schliessen') ?></button>
                <a class="btn btn-danger" href="<?php
                echo $this->url('langroute/config/default', array(
                    'controller' => 'testimonial', 'action' => 'delete', 'id' => $testimonial->getId()))
                ?>">
                    <span class="glyphicon glyphicon-remove"></span> <?php echo $this->translate('Löschen') ?>
                </a>
            </div>
        </div>
    </div>
</div>