<div class="page-header">
    <div class=" btn-toolbar pull-right">
        <a class="btn btn-info" href="<?php echo $this->url('langroute/config/default', array('controller' => 'location', 'action' => 'add')) ?>">
            <span class="glyphicon glyphicon-plus"></span> <?php echo $this->translate('Hinzufügen') ?>
        </a>
    </div>
    <h1 class=""><?php echo $this->translate('Mitarbeiter') ?></h1>
</div>
<div class="table-responsive">
    <table class="table  table-striped">
        <thead>
            <tr>
                <th><?php echo $this->translate('') ?></th>    
                <th><?php echo $this->translate('#ID') ?></th>
                <th><?php echo $this->translate('Name') ?></th>
                <th><?php echo $this->translate('Webseite') ?></th>
                <th><?php echo $this->translate('Strasse') ?></th>
                <th><?php echo $this->translate('Nr.') ?></th>
                <th><?php echo $this->translate('PLZ') ?></th>
                <th><?php echo $this->translate('Ort') ?></th>
                <th><?php echo $this->translate('Land') ?></th>
                <th><?php echo $this->translate('Akitv') ?></th>      
            </tr>
        </thead>
        <tbody>

            <?php
            foreach ($locations as $location) {
                ?>
                <tr>
                    <td> 
                        <a class="btn btn-xs" href="<?php
                        echo $this->url('langroute/config/default', array(
                            'controller' => 'location', 'action' => 'edit', 'id' => $location->getId()))
                        ?>">
                            <span class="glyphicon glyphicon-edit"></span> <?php echo $this->translate('Ändern') ?>
                        </a>
                        <button type="button" class="btn btn-danger btn-xs" data-toggle="modal" data-target="#delete">
                            <?php echo $this->translate('Löschen') ?>
                        </button>
                    </td>
                    <td><?php echo $location->getID() ?></td>
                    <td><?php echo $location->getName() ?></td>
                    <td><?php echo $location->getWebsite() ?></td>
                    <td><?php echo $location->getAddress()->getStreet() ?></td>
                    <td><?php echo $location->getAddress()->getNumber() ?></td>
                    <td><?php echo $location->getAddress()->getPostalcode() ?></td>
                    <td><?php echo $location->getAddress()->getPlace() ?></td>
                    <td><?php echo $location->getAddress()->getCountry() ?></td>
                    <td><?php echo $this->ActiveHelper($location->getActive()) ?></td>
                </tr>
            <?php } ?>
        </tbody>
    </table>
</div>

<div class="modal fade" id="delete" tabindex="-1" role="dialog" aria-labelledby="<?php echo $this->translate('Location löschen') ?>">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel"><?php echo $this->translate('Benutzer löschen') ?></h4>
            </div>
            <div class="modal-body">
                <?php echo $this->translate('Beim Bestätigen wird das Location endgültig vom System gelöscht. Danach kann Dieses nicht mehr Wiederhergestellt werden.') ?>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal"><?php echo $this->translate('Schliessen') ?></button>
                <a class="btn btn-danger" href="<?php
                echo $this->url('langroute/config/default', array(
                    'controller' => 'location', 'action' => 'delete', 'id' => $location->getId()))
                ?>">
                    <span class="glyphicon glyphicon-remove"></span> <?php echo $this->translate('Löschen') ?>
                </a>
            </div>
        </div>
    </div>
</div>