<div class="">
    <img  class="img-responsive center-block" src="<?php echo $this->basePath('img/sentru_ban_about.png') ?>" alt="Sentru Logo"/>
</div>


<div class="row">
    <div class="col-md-6">
        <div class="panel">
            <div class="panel-heading">
                <h3>Beat Rohr<br>Inhaber / Trainer</h3>
            </div>
            <div class="row">
                <div class="col-xs-4">
                    <img  class="img-head" src="<?php echo $this->basePath('img/Sentru_Beat_Kopf.png') ?>" alt="Beat Rohr"/>
                </div>
                <div class="col-xs-8">
                    <p class="text-justify">
                        Seine Karriere führte Beat Rohr von Verkaufsleiterpositionen in internationalen Unternehmen in der Automatisierungs-technik bis zu General Management Funktionen als CEO, Managing Director Schweiz im Telekommunikationssektor. Er verfügt über langjährige Erfahrung im Investitionsgüterbereich, der Mitarbeiterführung, Task Force Management und Change Management. Beat Rohr hat Elektronik studiert und sich an der Universität St.Gallen im Bereich Verkauf und Marketing weitergebildet.
                        <br>
                        Dank Natural Horsemanship lernte er nicht nur Pferde besser zu verstehen, sondern erkannte auch die Parallelen von Leadership mit Pferden und Management. 
                    </p>    
                    <br>
                    <p class="text-primary">
                        „In meiner Freizeit bin ich ein begeisterter Reiter. Meine Pferde, die nicht die einfachsten waren, lehrten mich Wichtiges im Bereich Leadership. Das Gelernte konnte ich täglich in meiner Führungsarbeit einsetzen.“ 
                    <p>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="panel">
            <div class="panel-title">
                <h3>Thomas Schneider<br>Partner / Trainer</h3>
            </div>
            <div class="panel-body">
                <div class="row-fluid">
                    <div class="col-xs-4">
                        <img  class="img-head" src="<?php echo $this->basePath('img/Sentru_Thomas_Kopf.png') ?>" alt="Thomas Schneider"/>
                    </div>
                    <div class="col-xs-8">
                        <p class="text-justify">
                            Als Moderator, Sparringspartner und Trainer begleitet Thomas Schneider seit über zehn Jahren Unternehmen, Teams und Einzelpersonen in Veränderungs- und Entwicklungsprozessen. Seine Kunden aus den Bereichen Industrie, Finanz, Telekom, Bau, Dienstleistung, Pharma und Verwaltung schätzen seine fundierte, zielorientierte und pragmatische Vorgehensweise.

                            Neben einem Studium in Betriebswirtschaft sowie einem MBA in Organisationsentwicklung und Change Management absolvierte er diverse Aus- und Weiterbildungen im psychologischen Bereich. 
                        </p>
                        <br>
                        <p class=" text-primary text-justify" >
                            „Es ist absolut faszinierend zu erleben, wie dieses Pferd neben dir ganz offensichtlich deine innerste Befindlichkeit erfasst. Es scheint fast so, als ob es deine Gedanken lesen könnte.“ 
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div> 
</div>
<div class="panel panel-info">
    <div class="panel-body alert-info">
        <p class="text-justify">
            Leadership hat viel mit emotionaler Fitness, Ehrlichkeit und Präsenz zu tun. Genau diese Eigenschaften fordert ein Pferd vom Menschen. Zusammenarbeit mit Pferden verlangt Klarheit ohne Worte.
        </p> 
    </div>
</div>

