<div class="">
    <img  class="img-responsive center-block" src="<?php echo $this->basePath('img/sentru_ban_impulsdays.png') ?>" alt="Sentru Logo"/>
</div>
<h3>
    Termine Impulstage
</h3>
<p class="text-justify text-primary">
    An den Impulstagen erhalten sie als Kunde einen Einblick in die SENTRU Leadership Seminare, die individuellen Teambulding Workshops, Assessments  und erleben die Effizenz der Reflektion mit den Pferden. 
</p>
<br>
<p>
    Interessiert? <a href="<?php echo $this->url('contact') ?>"> <?php echo $this->translate(' Kontaktieren Sie uns') ?></a>.
</p>

<div class="panel panel-default">
    <div class="panel-heading">Termin Übersicht</div>
    <div class="panel-body">
        <p style="text-justify">In der untenstehenden Tabellen finden Sie die bekannten Daten für die Druchführung der geplanten Seminare.</p>
    </div>

    <!-- Tabelle -->
    <table class="table-responsive table-striped">
        <thead>
            <tr>
                <th>Datum</th>
                <th>Uhrzeit</th>
                <th>Location</th>
                <th>Satus</th>
            </tr>
        </thead>
        <tbody>
            ___________
            <tr>
                <td>9. März</td>
                <td>15:00 - 17:00</td>
                <td>  Erushof, Sarmenstorf</td>
            </tr>

            <tr>
                <td>8. April</td>
                <td>14:00 - 17:00</td>
                <td>Hofgut Albführen, Dettighofen</td>
            </tr>

            <tr>
                <td>30. April</td>
                <td>14:00 - 17:00</td>
                <td>Hofgut Albführen, Dettighofen</td>
            </tr>

            <tr>
                <td>9. Juni</td>
                <td>10:00 - 13:00</td>
                <td>Hofgut Albführen, Dettighofen</td>
            </tr>
            <tr>
                <td>9. Juni</td>
                <td>14:00 - 17:00</td>
                <td>Hofgut Albführen, Dettighofen</td>
            </tr>
            <tr>
                <td> 9. September</td>
                <td>  10:00 - 13:00</td>
                <td>  Hofgut Albführen, Dettighofen</td>
            </tr>
            <tr>  
                <td>14. Oktober</td>        
                <td> 10:00 - 13:00</td>
                <td> Hofgut Albführen, Dettighofen</td>
            </tr>
        </tbody>
    </table>
</div>

