<div class="">
    <img  class="img-responsive center-block" src="<?php echo $this->basePath('img/sentru_ban_impulsdays.png') ?>" alt="Sentru Logo"/>
</div>
<h3>
    Termine Impulstage
</h3>
<p class="text-justify text-primary">
An den Impulstagen erhalten sie als Kunde einen Einblick in die SENTRU Leadership Seminare, die individuellen Teambulding Workshops, Assessments  und erleben die Effizenz der Reflektion mit den Pferden. 
</p>
<br>
<p>
Interessiert? <a href="<?php echo $this->url('contact') ?>"> <?php echo $this->translate('Kontaktieren Sie uns') ?></a>.
</p>


