<div class="">
    <img  class="img-responsive center-block" src="<?php echo $this->basePath('img/sentru_ban_index.png') ?>" alt="Sentru Logo"/>
</div>
<br>
<!-- End of banner image -->

<!-- Here Starts the content-->
<div class="row">
    <div class="col-md-6">
        <div class="panel">
            <!--    <div class="panel-title">
                    <h3>Sentru Imagefilm</h3>
                </div> -->
            <div class="panel-body">
                <video class="video" alt="Sentru Imagefilm" controls autoplay="true" loop="true">
                    <source src="video/sentru-hd.mp4" >
                </video>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="panel">
            <div class="panel-title">
                <h3> Testimonial </h3>
            </div>
            <div class="panel-body">
                <p>
                    «Ich habe schon an vielen Kommunikations-Trainings teilgenommen. Ein Pferd als „Coach“ war jedoch ein Novum und mit seinen 600 Kilogramm auch entsprechend imposant. Vielen Dank für den super organisierten Event und für die unvergesslichen Erkenntnisse. Gerne empfehle ich die SENTRU Workshops in meinem Bekanntenkreis weiter»
                </p> 
                <br>
                <p style="font-weight: bold">
                    Christian Unternährer, Inhaber, UP Personalvermittlung
                </p>
            </div>
        </div>
    </div> 
</div><!-- END ROW<-->
<!-- END OF FIRST ROW-->


<div class="row">
    <div class="col-md-6">
        <div class="panel">
            <div class="panel-heading">
                <h3>Beat Rohr / Trainer</h3>
            </div>
            <div class="row">
                <div class="col-xs-4">
                    <img  class="img-head" src="<?php echo $this->basePath('img/Sentru_Beat_Kopf.png') ?>" alt="Beat Rohr"/>
                </div>
                <div class="col-xs-8">
                    <p>
                        "Stärke deine Stärken, handle ehrlich und mit emotionaler Fitness.“
                    </p>    
                    <br>
                    <blockquote>
                        Mit diesem Motto führte Beat Rohr bereits als CEO, Managing Director und Verwaltungsrat erfolgreich internationale Firmen. In seiner Verantwortung lagen mehrstellige Millionenbeträge, Neuausrichtung von Unternehmen sowie notwendiges Change-Management. Sein Know-how über Pferde basiert auf der Philosophie von Natural Horsemanship.
                    </blockquote>

                </div>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="panel">
            <div class="panel-title">
                <h3>Thomas Schneider / Trainer</h3>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-xs-4">
                        <img  class="img-head" src="<?php echo $this->basePath('img/Sentru_Thomas_Kopf.png') ?>" alt="Thomas Schneider"/>
                    </div>
                    <div class="col-xs-8">
                        <p>
                            "Love it, change it or leave it."
                            <br>oder wie es Napoleon I. sagte: "Was soll das heissen - die Umstände? Ich bestimme, welche Umstände herrschen."
                        </p>
                        <br>
                        <blockquote>
                            Thomas Schneider verfügt über langjährige Erfahrung in den Bereichen Coaching, Führungs- und Kommunikationstraining, Change Management und Assessment. Er ist Inhaber von thomas schneider moderation-coaching-training sowie von 3HOME executive search.
                        </blockquote>
                    </div>
                </div>
            </div>
        </div>
    </div> 
</div><!-- END ROW<-->
<!-- END OF SECOND ROW<-->
<div class="text-info text-center">
    <h3>Wieso pferdegestütztes Management-Training?</h3>
    <p>Pferde begegnen dem Menschen vorurteilsfrei mit Vertrauen und Ehrlichkeit. Sie nehmen ihr Gegenüber sekundenschnell wahr und erkennen das Führungspotential. Mit ihrem Verhalten geben sie uns Auskunft über natürliche Autorität, sicheres Auftreten, aufgesetztes Verhalten, Unsicherheit und emotionale Fitness. Pferde geben dem Menschen direktes und ehrliches Feedback. 
    </p>
</div>

