<div class="">
    <img  class="img-responsive center-block" src="<?php echo $this->basePath('img/sentru_ban_leadership.png') ?>" alt="Sentru Logo"/>
</div>

<div class="row">
    <div class="col-md-6">
        <div class="panel">
            <div class="panel-title">
                <h3>Pferde erwarten Führung</h3>
            </div>
            <div class="panel-body">
                <p class="text-justify">
                    Pferde leben in klar strukturierten, hierarchischen Herden. Sie kommunizieren untereinander fast ausschliesslich über die Körpersprache. Sind beim Menschen die verbalen und nonverbalen Botschaften kongruent, akzeptiert das Pferd die Führung. Arbeitet man fokussiert, mit Vertrauen und Respekt, zeigt das Pferd Kooperation und Leistung. Werden Sie sich Ihrer Gedanken und Handlungen bewusst, schärfen Sie Ihre Wahrnehmung und lernen Sie, planerisch und transparent vorgehen sowie bewusst, gezielt und situativ zu führen. 
                </p> 
            </div>
        </div>
    </div> 
    <div class="col-md-6">
        <div class="panel">
            <div class="panel-title">
                <h3>Testimonial</h3>
            </div>
            <div class="panel-body">
                <p>
                    «Am Überraschendsten war zu sehen, dass das gleiche Pferd auf jeden Menschen anders reagierte. Und sobald die Person ihr Verhalten änderte, änderte sich auch die Reaktion des Pferdes. Das Pferd als Spiegel – ein aus meiner Sicht äusserst nützliches und effizientes Hilfsmittel für Assessments» 
                </p> 
                <br>
                <p style="font-weight: bold">
                    Rene Achermann, Inhaber, ppa Communication GmbH 
                </p>
            </div>
        </div>
    </div> 
</div>
<div class="row">
    <div class="col-md-6">
        <div class="panel panel-info">
            <div class="panel-body alert-info">
                <p class="text-justify">
                    In diesen Seminare erfahren Sie mehr über Ihren Führungsstil, Ihre Führungsqualitäten sowie Ihr Entwicklungspotenzial. Erfahren Sie Leadership! 
                </p> 
            </div>
        </div>
    </div> 
    <div class="col-md-6">
        <div class="panel">
            <div class="panel-title">
                <h3>Überblick</h3>
            </div>
            <div class="panel-body">
                <p class="text-justify">
                    Die Seminare werden in Gruppendurchgeführt und steht sowohl Einzelpersonen wie auch Firmengruppen offen. Im Vorfeld erfolgt eine Bedürfnisabklärung bei den einzelnen Personen oder Gruppen. Die im Seminarraum erarbeiteten Themen werden anschliessend mit den Pferden praktisch erlebt und reflektiert. 
                </p> 
            </div>
        </div>
    </div> 
</div>
<div class="row-fluid">
    <h3>Mehr Informationen</h3>
    <div class="col-lg-6">
        <br>
        <iframe class="" width="512px" height="384px" src="https://www.yumpu.com/de/document/embed/YyVfL97N2g55WGAc" frameborder="0" allowfullscreen="true" allowtransparency="true"></iframe>
    </div>
    <div class="col-lg-6">
        <br>
        <iframe class="" width="512px" height="384px" src="https://www.yumpu.com/de/embed/view/fRSvSnmTWDFTUQJs"  frameborder="0" allowfullscreen="true" allowtransparency="true"></iframe>
    </div>
</div>
