<div class="">
    <img  class="img-responsive center-block" src="<?php echo $this->basePath('img/sentru_ban_location.png') ?>" alt="Sentru Logo"/>
</div>
<div class="panel panel-info">
    <div class="panel-body alert-info">
        <p class="text-justify">
            Sie schildern uns Ihre Bedürfnisse und wir organisieren für Sie die geeignete Location. Mit unserem Partnernetzwerk sind wir in der Lage, die Seminare in der Schweiz, in Deutschland, Österreich und Ungarn durchzuführen. 
        </p> 
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <h3>Hofgut Albführen,<br> Süddeutschland</h3>
        <div class="row">
            <div class="col-sx-6">
                <img  class="img-loc" src="<?php echo $this->basePath('img/Alp_F_1.png') ?>" alt="Hofgut Albführen"/>
            </div>
            <div class="col-sx-6">

            </div>
        </div>
    </div>
</div>


