<div class="">
    <img  class="img-responsive center-block" src="<?php echo $this->basePath('img/sentru_ban_seminare.png') ?>" alt="Sentru Logo"/>
</div>
<div class="row">
    <div class="col-md-6">
        <div class="panel">
            <div class="panel-title">
                <h3>Pferde erkennen Persönlichkeiten</h3>
            </div>
            <div class="panel-body">
                <p class="text-justify">
                    Pferde leben in der Gegenwart und bewerten uns und unsere Handlungen unabhängig vom Gestern jeden Tag neu. Taktieren, Tricks oder einstudierte Muster werden Pferde sofort erkennen und unmittelbar reflektieren. Mit ihrer sensiblen Wahrnehmung reagieren sie auf die Wirkung eines Menschen. Im Umgang mit Pferden werden Führungsqualitäten, emotionale Fitness, persönliche und soziale Kompetenzen sichtbar. 
                </p> 
            </div>
        </div>
    </div> 
    <div class="col-md-6">
        <div class="panel">
            <div class="panel-title">
                <h3>Testimonial</h3>
            </div>
            <div class="panel-body">
                <p>
                    «Am Überraschendsten war zu sehen, dass das gleiche Pferd auf jeden Menschen anders reagierte. Und sobald die Person ihr Verhalten änderte, änderte sich auch die Reaktion des Pferdes. Das Pferd als Spiegel – ein aus meiner Sicht äusserst nützliches und effizientes Hilfsmittel für Assessments» 
                </p> 
                <br>
                <p style="font-weight: bold">
                    Rene Achermann, Inhaber, ppa Communication GmbH 
                </p>
            </div>
        </div>
    </div> 
</div>
<div class="row">
    <div class="col-md-6">
        <div class="panel panel-info">
            <div class="panel-body alert-info">
                <p class="text-justify">
                    Pferde leben in der Gegenwart und bewerten uns und unsere Handlungen unabhängig vom Gestern jeden Tag neu. Taktieren, Tricks oder einstudierte Muster werden Pferde sofort erkennen und unmittelbar reflektieren. Mit ihrer sensiblen Wahrnehmung reagieren sie auf die Wirkung eines Menschen. Im Umgang mit Pferden werden Führungsqualitäten, emotionale Fitness, persönliche und soziale Kompetenzen sichtbar. 
                </p> 
            </div>
        </div>
    </div> 
    <div class="col-md-6">
        <div class="panel">
            <div class="panel-title">
                <h3>Überblick</h3>
            </div>
            <div class="panel-body">
                <p class="text-justify">
                    In den Seminaren und Workshops sowie bei den Assessment bilden die Übungen mit den Pferden einen festen Bestandteil des Programms. Hier erhalten Sie weitere Information zu den Leadership Seminare, Teambuliding Workshops und Assessment. 
                </p> 
            </div>
        </div>
    </div> 
</div>
<br>
<div class="row-fluid">
    <h3>Mehr Informationen</h3>
    <div class="col-lg-6">
        <br>
        <iframe class="" width="512px" height="384px" src="https://www.yumpu.com/de/document/embed/YyVfL97N2g55WGAc" frameborder="0" allowfullscreen="true" allowtransparency="true"></iframe>
    </div>
    <div class="col-lg-6">
        <br>
        <iframe class="" width="512px" height="384px" src="https://www.yumpu.com/de/embed/view/fRSvSnmTWDFTUQJs"  frameborder="0" allowfullscreen="true" allowtransparency="true"></iframe>
    </div>
</div>

