<div class="">
    <img  class="img-responsive center-block" src="<?php echo $this->basePath('img/sentru_ban_team.png') ?>" alt="Sentru Logo"/>
</div>

<div class="row">
    <div class="col-md-6">
        <div class="panel">
            <div class="panel-title">
                <h3>Pferde – hochsensible Sozialwesen</h3>
            </div>
            <div class="panel-body">
                <p class="text-justify">
                    Als Herden- und Fluchttiere sind Pferde genetisch darauf programmiert, ihre Umgebung und das Gegenüber äusserst sensibel wahrzunehmen. Fairness, Vertrauen und planerische Fähigkeiten sind im Umgang mit Pferden sehr wichtig. „Miteinander“ ist eine Voraussetzung für das Erreichen von Zielen.
                    <br>
                    Konflikte, Unruhe oder Rücksichtslosigkeit werden vom Fluchttier wahrgenommen, als Schwäche erkannt und mit wenig Bereitschaft zur Kooperation beantwortet.
                </p> 
            </div>
        </div>
    </div> 
    <div class="col-md-6">
        <div class="panel">
            <div class="panel-title">
                <h3>Testimonial</h3>
            </div>
            <div class="panel-body">
                <p>
                    «Am Überraschendsten war zu sehen, dass das gleiche Pferd auf jeden Menschen anders reagierte. Und sobald die Person ihr Verhalten änderte, änderte sich auch die Reaktion des Pferdes. Das Pferd als Spiegel – ein aus meiner Sicht äusserst nützliches und effizientes Hilfsmittel für Assessments» 
                </p> 
                <br>
                <p style="font-weight: bold">
                    Rene Achermann, Inhaber, ppa Communication GmbH 
                </p>
            </div>
        </div>
    </div> 
</div>
<div class="row">
    <div class="col-md-6">
        <div class="panel panel-info">
            <div class="panel-body alert-info">
                <p class="text-justify">
                    Themen sind Performance-Steigerung, Stärkung des Teamspirits, Verbesserung der Kommunikation oder das Einschwören des Team auf die anstehende Aufgabe. Erleben Sie Teamspirit! 
                </p> 
            </div>
        </div>
    </div> 
    <div class="col-md-6">
        <div class="panel">
            <div class="panel-title">
                <h3>Überblick</h3>
            </div>
            <div class="panel-body">
                <p class="text-justify">
                    Die Teambuilding-Workshops finden individuell und abgestimmt auf Ihre Bedürfnisse und Ihre Thematik statt. Im Vorgespräch erörtern wir gemeinsam die Situation und die Zielsetzung. Das Team setzt sich dann mit Aufgaben für die Zielerreichung in praktischen Übungen auseinander und erlebt diese durch Reflektionen mit den Pferden. Follow-up Gespräche erhöhen die Nachhaltigkeit des Erreichten und gewährleisten den Transfer in den Arbeitsalltag. 
                </p> 
            </div>
        </div>
    </div> 
</div>
<div class="row-fluid">
    <h3>Mehr Informationen</h3>
    <div class="col-lg-6">
        <br>
        <iframe class="" width="512px" height="384px" src="https://www.yumpu.com/de/document/embed/YyVfL97N2g55WGAc" frameborder="0" allowfullscreen="true" allowtransparency="true"></iframe>
    </div>
    <div class="col-lg-6">
        <br>
        <iframe class="" width="512px" height="384px" src="https://www.yumpu.com/de/embed/view/fRSvSnmTWDFTUQJs"  frameborder="0" allowfullscreen="true" allowtransparency="true"></iframe>
    </div>
</div>

<div class="row-fluid">
    <h3>Mehr Informationen</h3>
    <div class="col-lg-6">
        <br>
        <iframe class="" width="512px" height="384px" src="https://www.yumpu.com/de/document/embed/YyVfL97N2g55WGAc" frameborder="0" allowfullscreen="true" allowtransparency="true"></iframe>
    </div>
    <div class="col-lg-6">
        <br>
        <iframe class="" width="512px" height="384px" src="https://www.yumpu.com/de/embed/view/fRSvSnmTWDFTUQJs"  frameborder="0" allowfullscreen="true" allowtransparency="true"></iframe>
    </div>
</div>