
<div class="banner">
    <img class="img-responsive center" src="/img/SENTRU_ban_index.png">
</div>


<!-- START TEST -->  

<script type="text/javascript">
    $(document).ready(function () {
        $('#carousel-example.slide').carousel({
            interval: 7000,
            pause: "hover"
        });

        $('input').focus(function () {
            $("#carousel-example").carousel('pause');
        }).blur(function () {
            $("#carousel-example").carousel('cycle');
        });

    });
</script>

<div id="carousel-example" class="carousel slide" data-ride="carousel">
    <!-- Wrapper for slides -->
    <div class="row">
        <div class="col-xs-offset-2 col-xs-8">
            <!--            <div>
                            <img class="preview" src="https://www.magicload.ch/images/pics/swisscom-logo_png.png">
                            <img class="preview" src="http://www.designtagebuch.de/wp-content/uploads/mediathek//2015/04/salt-logo-700x400.gif"> 
                        </div>-->
            <div class="carousel-inner">  
                <?php
                $i = 1;
                foreach ($testimonials as $testimonial) {
                    if ($testimonial->getActive()) {
                        ?>
                        <div class="item<?php
                        if ($i == 1) {
                            echo ' active';
                        }
                        ?> ">
                            <div class="carousel-content">
                                <div id="<?php echo $testimonial->getId() ?>">                            
                                    <p>«<?php echo $testimonial->getStatement() ?>»</p>
                                    <h4><?php
                                        echo $testimonial->getFirstname();
                                        echo $testimonial->getLastname() . ', ' . $testimonial->getPosition() . ', ' . $testimonial->getCompany()
                                        ?></h4>
                                    <img class="" src="<?php echo $testimonial->getLogo()->getPath() ?>">
                                </div>
                            </div>
                        </div>               
                        <?php
                        $i++;
                    }
                }
                ?>
            </div>
        </div>
    </div>
    <!-- Controls --> <a class="left carousel-control" href="#carousel-example" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left"></span>
    </a>
    <a class="right carousel-control" href="#carousel-example" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right"></span>
    </a>
</div>


<div class="row">
    <?php
    foreach ($employees as $employee) {
        echo $this->EmployeeHelper($employee);
    }
    ?>
</div>
