<div class="container">
    <div class="banner">
        <img class="img-responsive center" src="/img/SENTRU_ban_index.png">
    </div>


    <!-- START TEST -->  
    <div class="col-md-12">
        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
            <!-- Indicators -->
            <ol class="carousel-indicators">
                <!--                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                                <li data-target="#carousel-example-generic" data-slide-to="1"></li>-->
                <li   data-target="#carousel-example-generic" data-slide-to="0"class="active"></li>
                <li data-target="#carousel-example-generic"  data-slide-to="1"></li>

            </ol>

            <!-- Wrapper for slides -->
            <div class="carousel-inner" role="listbox">
                <?php
                $i = 1;
                foreach ($testimonials as $testimonial) {
                    ?>
                    <div class="item <?php
                    if ($i == 1) {
                        echo 'active';
                    }
                    ?>">
                        <i class="text-justify">"<?php echo $testimonial->getStatement() ?>"</i>
                        <div class="">
                            <img class="img-responsive logo" src="<?php echo $testimonial->getLogo()->getPath() ?>">
                        </div>
                    </div>

                    <?php
                    $i++;
                }
                ?>
            </div>

            <!-- Controls -->
            <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
<!--                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>-->
                <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
<!--                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>-->
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>
    <!-- END TEST -->  



    <div class="row">
        <?php
        foreach ($employees as $employee) {
            echo $this->EmployeeHelper($employee);
        }
        ?>
    </div>
</div>